parameters:
    netvlies_routing.redirect_router.class: Symfony\Cmf\Bundle\RoutingExtraBundle\Routing\DynamicRouter
    netvlies_routing.redirect_route_entity.class: Netvlies\Bundle\RouteBundle\Document\RedirectRoute
    netvlies_routing.redirect_routing.repository_root: /netvlies/redirects
    netvlies_routing.phpcrodm_route_idprefix_listener.class: Symfony\Cmf\Bundle\RoutingExtraBundle\Listener\IdPrefix
    netvlies_routing.redirect_controller.class: Symfony\Cmf\Bundle\RoutingExtraBundle\Controller\RedirectController #Netvlies\Bundle\RouteBundle\Controller\RedirectRouteController

services:

    netvlies_routing.phpcrodm_route_idprefix_listener:
        class: %netvlies_routing.phpcrodm_route_idprefix_listener.class%
        arguments: [ %netvlies_routing.redirect_routing.repository_root% ]
        tags:
            - {name: doctrine_phpcr.event_listener, event: postLoad }
            - {name: doctrine_phpcr.event_listener, event: postPersist }

    netvlies_routing.redirect_route_repository:
        class: Netvlies\Bundle\RouteBundle\Document\RedirectRouteRepository
        arguments: [ @symfony_cmf_routing_extra.manager_registry, %netvlies_routing.redirect_route_entity.class% ]
        calls:
            - [ setPrefix,[ %netvlies_routing.redirect_routing.repository_root% ]]

    netvlies_routing.redirect_router:
        class: %netvlies_routing.redirect_router.class%
        arguments: [ @netvlies_routing.redirect_route_repository ]
        calls:
            - [ setContext, [ @router.request_context ] ]
            - [ setContainer, [ @service_container ] ]
            - [ setContentRepository, [ @symfony_cmf_routing_extra.content_repository ] ]

    netvlies_routing.route_service:
        class: Netvlies\Bundle\RouteBundle\Routing\RouteService
        arguments: [ @service_container ]

    netvlies_admin.admin.route:
        class: Netvlies\Bundle\RouteBundle\Admin\RouteAdmin
        tags:
            - {name: sonata.admin, manager_type: doctrine_phpcr, group: URL-beheer, label: URL's, show_in_dashboard: false}
        arguments: ["",Netvlies\Bundle\RouteBundle\Document\Route, SonataAdminBundle:CRUD]
        calls:
            - [ setRouteBuilder, [ @sonata.admin.route.path_info_slashes ] ]
            - [ setContainer, [ @service_container ] ]
            - [ setTranslationDomain, [ NetvliesOmsBundle ] ]

    netvlies_admin.admin.redirect_route:
        class: Netvlies\Bundle\RouteBundle\Admin\RedirectRouteAdmin
        tags:
            - {name: sonata.admin, manager_type: doctrine_phpcr, group: URL-beheer, label: Redirects}
        arguments: ["",Netvlies\Bundle\RouteBundle\Document\RedirectRoute, SonataAdminBundle:CRUD]
        calls:
            - [ setRouteBuilder, [ @sonata.admin.route.path_info_slashes ] ]
            - [ setContainer, [ @service_container ] ]
            - [ setTranslationDomain, [ NetvliesOmsBundle ] ]

    netvlies_routing.document_matcher:
        class: Netvlies\Bundle\RouteBundle\Routing\MultiSiteDocumentMatcher
        calls:
            - [ setContainer, [ @service_container ] ]

    netvlies_routing.route_tab.admin_extension:
        class: Netvlies\Bundle\RouteBundle\Admin\Extension\RouteTabAdminExtension
        calls:
            - [ setContainer, [ @service_container ] ]

    netvlies_routing.route_subscriber:
        class: Netvlies\Bundle\RouteBundle\Doctrine\Listener\RouteSubscriber
        arguments: [ @service_container ]
        tags:
            - { name: doctrine_phpcr.event_subscriber, connection: default }

    netvlies_routing.route_aware_subscriber:
        class: Netvlies\Bundle\RouteBundle\Doctrine\Listener\RouteAwareSubscriber
        arguments: [ @service_container ]
        tags:
            - { name: doctrine_phpcr.event_subscriber, connection: default }

    netvlies_routing.annotation_driver:
        class: Netvlies\Bundle\RouteBundle\Mapping\Driver\AnnotationDriver
        public: false
        arguments: [ @annotation_reader ]


    netvlies_routing.metadata_cache:
        class: Metadata\Cache\FileCache
        public: false
        arguments: [cache]
        # set cache directory in extension


    netvlies_routing.metadata_factory:
        class: Metadata\MetadataFactory
        arguments: [ @netvlies_routing.annotation_driver ]
        calls:
            - [ setCache, [ @netvlies_routing.metadata_cache ] ]

    netvlies_routing.redirect_controller:
        class: %netvlies_routing.redirect_controller.class%
        arguments: [ @router ]
